### PR TITLE
add option to install bash to xbin

### PR DESCRIPTION
**Pull request by skittles9823**

### CODE REVIEW

**Comment by Zackptg5** [comment]
Why is this needed?

**Comment by skittles9823** [comment]
On my rom (AOSiP) bash is already in xbin. If I flash the module, my phone bootloops for some reason unless I make the module overlay the preexisting bash.

**Comment by Zackptg5** [comment]
Odd. I think an easier method would be to install to bin unless bash is detected in xbin, then there's no need to prompt the user

**Comment by Zackptg5** [comment]
Fixed in commit 9def6276e89cbb220c5666e3f2ee1a7f0833fff1

**Pull request closed without merging**
